baseurl = "http://ulricqin.com"
languageCode = "zh-cn"
title = "Ulric Qin"
theme = "hyde"

[Taxonomies]
    tag = "tags"

[params]
    disqus = "ulricqin"
    abc = "Talk is cheap. Show me the code."


